CREATE  TABLE dbo.TblESTADO ( 
	ID_ESTADO            int    IDENTITY  NOT NULL,
	NM_ESTADO            varchar(30)      NULL,
	DS_SIGLA             char(2)      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblEstado PRIMARY KEY  ( ID_ESTADO ) 
 );
GO

CREATE  TABLE dbo.TblLOG_ERRO ( 
	ID_LOG_ERRO          int      NOT NULL,
	DT_ERRO              datetime      NOT NULL,
	ID_USUARIO           varchar(max)      NOT NULL,
	NR_ERRO              varchar(max)      NOT NULL,
	DS_SEVERIDADE        int      NULL,
	DS_ESTADO            int      NOT NULL,
	DS_PROCEDIMENTO      int      NULL,
	NR_LINHA             int      NULL,
	DS_MENSAGEM          varchar(max)      NULL,
	CONSTRAINT pk_TblLOG_ERRO PRIMARY KEY  ( ID_LOG_ERRO ) 
 );
GO

CREATE  TABLE dbo.TblMULTIPLICADOR ( 
	ID_MULTIPLICADOR     int    IDENTITY  NOT NULL,
	ID_ESTADO_ORIGEM     int      NOT NULL,
	ID_ESTADO_DESTINO    int      NOT NULL,
	VL_MULTIPLICADOR     float      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblMULTIPLICADOR PRIMARY KEY  ( ID_MULTIPLICADOR ) ,
	CONSTRAINT unq_TblMULTIPLICADOR_NR_MULTIPLICADOR UNIQUE ( VL_MULTIPLICADOR ) 
 );
GO

CREATE  TABLE dbo.TblPRODUTO ( 
	ID_PRODUTO           int    IDENTITY  NOT NULL,
	NM_PRODUTO           varchar(max)      NULL,
	DS_CATEGORIA         varchar(max)      NULL,
	DS_SUBCATEGORIA      varchar(max)      NULL,
	NM_UNIDADE_DE_MEDIDA varchar(max)      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblCATEGORIA PRIMARY KEY  ( ID_PRODUTO ) 
 );
GO

CREATE  TABLE dbo.TblSTATUS ( 
	ID_STATUS            int    IDENTITY  NOT NULL,
	DS_STATUS            varchar(max)      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblSTATUS PRIMARY KEY  ( ID_STATUS ) 
 );
GO

CREATE  TABLE dbo.TblUSUARIO ( 
	ID_USUARIO           int    IDENTITY  NOT NULL,
	FL_TIPO_USUARIO      varchar(max)      NULL,
	DS_EMAIL             varchar(max)      NULL,
	DS_SENHA             varchar(max)      NULL,
	NR_TELEFONE          varchar(max)      NULL,
	NM_USUARIO           varchar(max)      NULL,
	NR_DOCUMENTO_LEGAL   varchar(max)      NULL,
	DT_NASCIMENTO        date      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblUSUARIO_0 PRIMARY KEY  ( ID_USUARIO ) 
 );
GO

CREATE  TABLE dbo.TblVEICULO ( 
	ID_VEICULO           int    IDENTITY  NOT NULL,
	ID_USUARIO           int      NOT NULL,
	TP_VEICULO           varchar(max)      NULL,
	NM_MARCA             varchar(max)      NULL,
	NM_MODELO            varchar(max)      NULL,
	DS_PLACA             varchar(8)      NULL,
	NR_CAPACIDADE        int      NULL,
	DT_ANO               numeric(4)      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblVEICULO PRIMARY KEY  ( ID_VEICULO ) 
 );
GO

CREATE  TABLE dbo.TblENDERECO ( 
	ID_ENDERECO          int    IDENTITY  NOT NULL,
	ID_ESTADO            int      NOT NULL,
	ID_USUARIO           int      NULL,
	NR_CEP               varchar(max)      NULL,
	NM_RUA               varchar(max)      NULL,
	NR_RUA               int      NULL,
	DS_COMPLEMENTO       varchar(max)      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblENDERECO PRIMARY KEY  ( ID_ENDERECO ) 
 );
GO

CREATE  TABLE dbo.TblPEDIDO ( 
	ID_PEDIDO            int    IDENTITY  NOT NULL,
	ID_USUARIO_CLIENTE   int      NOT NULL,
	ID_USUARIO_PRESTADOR int      NOT NULL,
	ID_ENDERECO          int      NOT NULL,
	ID_MULTIPLICADOR     int      NOT NULL,
	VL_PERC_FRETE        float      NULL,
	VL_FRETE             money      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblPEDIDO PRIMARY KEY  ( ID_PEDIDO ) 
 );
GO

CREATE  TABLE dbo.TblPRODUTO_PEDIDO ( 
	ID_PRODUTO_PEDIDO    int    IDENTITY  NOT NULL,
	ID_PEDIDO            int      NOT NULL,
	ID_PRODUTO           int      NOT NULL,
	FL_VALIDO            int      NULL,
	VL_MENSURADO         float      NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblPRODUTOS PRIMARY KEY  ( ID_PRODUTO_PEDIDO ) 
 );
GO

CREATE  TABLE dbo.TblSTATUS_PEDIDO ( 
	ID_STATUS_PEDIDO     int    IDENTITY  NOT NULL,
	ID_PEDIDO            int      NOT NULL,
	ID_STATUS            int      NOT NULL,
	DT_INCLUSAO          datetime      NULL,
	CONSTRAINT pk_TblPEDIDO_STATUS PRIMARY KEY  ( ID_STATUS_PEDIDO ) 
 );
GO

ALTER TABLE dbo.TblENDERECO ADD CONSTRAINT fk_TblENDERECO_TblUSUARIO FOREIGN KEY ( ID_USUARIO ) REFERENCES dbo.TblUSUARIO( ID_USUARIO );
GO

ALTER TABLE dbo.TblENDERECO ADD CONSTRAINT fk_TblENDERECO_TblESTADO FOREIGN KEY ( ID_ESTADO ) REFERENCES dbo.TblESTADO( ID_ESTADO );
GO

ALTER TABLE dbo.TblMULTIPLICADOR ADD CONSTRAINT fk_TblMULTIPLICADOR_TblESTADO FOREIGN KEY ( ID_ESTADO_ORIGEM ) REFERENCES dbo.TblESTADO( ID_ESTADO );
GO

ALTER TABLE dbo.TblMULTIPLICADOR ADD CONSTRAINT fk_TblMULTIPLICADOR_TblESTADO_0 FOREIGN KEY ( ID_ESTADO_DESTINO ) REFERENCES dbo.TblESTADO( ID_ESTADO );
GO

ALTER TABLE dbo.TblPEDIDO ADD CONSTRAINT fk_TblPEDIDO_TblUSUARIO FOREIGN KEY ( ID_USUARIO_CLIENTE ) REFERENCES dbo.TblUSUARIO( ID_USUARIO );
GO

ALTER TABLE dbo.TblPEDIDO ADD CONSTRAINT fk_TblPEDIDO_TblUSUARIO_0 FOREIGN KEY ( ID_USUARIO_PRESTADOR ) REFERENCES dbo.TblUSUARIO( ID_USUARIO );
GO

ALTER TABLE dbo.TblPEDIDO ADD CONSTRAINT fk_TblPEDIDO_TblMULTIPLICADOR_0 FOREIGN KEY ( ID_MULTIPLICADOR ) REFERENCES dbo.TblMULTIPLICADOR( ID_MULTIPLICADOR );
GO

ALTER TABLE dbo.TblPEDIDO ADD CONSTRAINT fk_TblPEDIDO_TblENDERECO FOREIGN KEY ( ID_ENDERECO ) REFERENCES dbo.TblENDERECO( ID_ENDERECO );
GO

ALTER TABLE dbo.TblPRODUTO_PEDIDO ADD CONSTRAINT fk_TblPRODUTO_TblPEDIDO FOREIGN KEY ( ID_PEDIDO ) REFERENCES dbo.TblPEDIDO( ID_PEDIDO );
GO

ALTER TABLE dbo.TblPRODUTO_PEDIDO ADD CONSTRAINT fk_TblPRODUTO_PEDIDO_TblPRODUTO FOREIGN KEY ( ID_PRODUTO ) REFERENCES dbo.TblPRODUTO( ID_PRODUTO );
GO

ALTER TABLE dbo.TblSTATUS_PEDIDO ADD CONSTRAINT fk_TbSTATUS_PEDIDO_TblPEDIDO FOREIGN KEY ( ID_PEDIDO ) REFERENCES dbo.TblPEDIDO( ID_PEDIDO );
GO

ALTER TABLE dbo.TblSTATUS_PEDIDO ADD CONSTRAINT fk_TbSTATUS_PEDIDO_TblSTATUS FOREIGN KEY ( ID_STATUS ) REFERENCES dbo.TblSTATUS( ID_STATUS );
GO

ALTER TABLE dbo.TblVEICULO ADD CONSTRAINT fk_TblVEICULO_TblUSUARIO_0 FOREIGN KEY ( ID_USUARIO ) REFERENCES dbo.TblUSUARIO( ID_USUARIO );
GO
